hrms/hrms/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from reviews.views import HRMSRegistrationView

urlpatterns = [
    url(r'^accounts/register/', HRMSRegistrationView.as_view(), name='registration_register'),
    url(r'^reviews/', include('reviews.urls', namespace="reviews")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="auth")),
]

hrms/reviews/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /
    url(r'^$', views.review_list, name='review_list'),

    url(r'^staff$', views.staff_list, name='staff_list'),
    url(r'^predictedList$', views.predicted_list, name='predicted_list'),
    url(r'^empReviewedList', views.reviewed_list, name='reviewed_list'),
    url(r'^staff/(?P<staff_id>[0-9]+)/$', views.staff_detail, name='staff_detail'),
    url(r'^staff/(?P<staff_id>[0-9]+)/add_emp_review/$', views.add_emp_review, name='add_emp_review'),
    url(r'^emprecommendation/$', views.emp_recommendation_list, name='emp_recommendation_list'),
]

hrms/reviews/models.py
from django.db import models
from django.contrib.auth.models import User

class EmpReview(models.Model):
    SALARY_CHOICES = (
        (0, 'LOW'),
        (1, 'MEDIUM'),
        (2, 'HIGH'),
    )
    WORK_ACCIDENT_CHOICES = (
        (0, 'NO'),
        (1, 'YES'),
    )
    LEFT_CHOICES = (
        (0, 'NO'),
        (1, 'YES'),
    )
    PROMOTION_CHOICES = (
        (0, 'NO'),
        (1, 'YES'),
    )
    DEPARTMENT_CHOICES = (
        (0, 'sales'),
        (1, 'accounting'),
        (2, 'hr'),
        (3, 'technical'),
        (4, 'support'),
        (5, 'management'),
        (6, 'IT'),
        (7, 'product_mng'),
        (8, 'marketing'),
        (9, 'RandD'),
    )
    staff = models.ForeignKey(User)
    satisfaction_level = models.DecimalField(max_digits=3, decimal_places=2)
    last_evaluation = models.DecimalField(max_digits=3, decimal_places=2)
    number_project = models.IntegerField()
    average_montly_hours = models.IntegerField()
    time_spend_company = models.IntegerField()
    Work_accident = models.IntegerField(choices=WORK_ACCIDENT_CHOICES)
    left = models.IntegerField(choices=LEFT_CHOICES)
    promotion_last_5years = models.IntegerField(choices=PROMOTION_CHOICES)
    department =models.IntegerField(choices=DEPARTMENT_CHOICES)
    salary = models.IntegerField(choices=SALARY_CHOICES)
    user_name = models.CharField(max_length=100)
    review_date = models.DateField()
    
class EmpPossibleResigneeReview(models.Model):
    SALARY_CHOICES = (
        (0, 'LOW'),
        (1, 'MEDIUM'),
        (2, 'HIGH'),
    )
    WORK_ACCIDENT_CHOICES = (
        (0, 'NO'),
        (1, 'YES'),
    )
    LEFT_CHOICES = (
        (0, 'NO'),
        (1, 'YES'),
    )
    PROMOTION_CHOICES = (
        (0, 'NO'),
        (1, 'YES'),
    )
    DEPARTMENT_CHOICES = (
        (0, 'sales'),
        (1, 'accounting'),
        (2, 'hr'),
        (3, 'technical'),
        (4, 'support'),
        (5, 'management'),
        (6, 'IT'),
        (7, 'product_mng'),
        (8, 'marketing'),
        (9, 'RandD'),
    )

    satisfaction = models.DecimalField(max_digits=3, decimal_places=2)
    evaluation = models.DecimalField(max_digits=3, decimal_places=2)
    projectCount = models.IntegerField()
    averageMonthlyHours = models.IntegerField()
    yearsAtCompany = models.IntegerField()
    workAccident = models.IntegerField(choices=WORK_ACCIDENT_CHOICES)
    promotion = models.IntegerField(choices=PROMOTION_CHOICES)
    department =models.IntegerField(choices=DEPARTMENT_CHOICES)
    salary = models.IntegerField(choices=SALARY_CHOICES)
    turnover = models.IntegerField(choices=LEFT_CHOICES)

hrms/reviews/forms.py
from django.forms import ModelForm
from reviews.models import EmpReview

class EmpReviewForm(ModelForm):
    class Meta:
        model = EmpReview
        fields = ['satisfaction_level', 'last_evaluation', 'number_project', 'average_montly_hours', 'time_spend_company', 'Work_accident', 'left', 'promotion_last_5years', 'department', 
                'salary', 'review_date']
        labels = {
            'satisfaction_level': 'Satisfaction level'
        }

hrms/reviews/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import User
from .models import EmpReview, EmpPossibleResigneeReview
from .forms import EmpReviewForm
from .suggestions import train_Algorithm
from .tables import StaffTable, PossibleResigneeTable, ReviewedEmployeeTable
from django_tables2 import RequestConfig
from registration.backends.simple.views import RegistrationView
from django.contrib.auth.decorators import login_required


def review_list(request):
    return render(request, 'reviews/review_list.html')

@login_required
def staff_list(request):
    staff_list = StaffTable(User.objects.all())
    RequestConfig(request).configure(staff_list)
    return render(request, 'reviews/staff_list.html', {'staff_list': staff_list})

@login_required
def predicted_list(request):
    predicted_list = PossibleResigneeTable(EmpPossibleResigneeReview.objects.all())
    RequestConfig(request).configure(predicted_list)
    return render(request, 'reviews/predicted_list.html', {'predicted_list': predicted_list})

@login_required
def reviewed_list(request):
    reviewed_list = ReviewedEmployeeTable(EmpReview.objects.all())
    RequestConfig(request).configure(reviewed_list)
    return render(request, 'reviews/reviewed_list.html', {'reviewed_list': reviewed_list})

def staff_detail(request, staff_id):
    staff = get_object_or_404(User, pk=staff_id)
    form = EmpReviewForm()
    return render(request, 'reviews/staff_detail.html', {'staff': staff, 'form': form})

@login_required
def add_emp_review(request, staff_id):
    staff = get_object_or_404(User, pk=staff_id)
    form = EmpReviewForm(request.POST)
    if form.is_valid():
        user_name = request.user.username
        review = EmpReview()
        review.staff = staff
        review.satisfaction_level = form.cleaned_data['satisfaction_level']
        review.last_evaluation = form.cleaned_data['last_evaluation']
        review.number_project = form.cleaned_data['number_project']
        review.average_montly_hours = form.cleaned_data['average_montly_hours']
        review.time_spend_company = form.cleaned_data['time_spend_company']
        review.Work_accident = form.cleaned_data['Work_accident']
        review.left = form.cleaned_data['left']
        review.promotion_last_5years = form.cleaned_data['promotion_last_5years']
        review.department = form.cleaned_data['department']
        review.salary = form.cleaned_data['salary']
        review.user_name = user_name
        review.review_date = form.cleaned_data['review_date']
        review.save()

    reviewed_list = ReviewedEmployeeTable(EmpReview.objects.all())
    RequestConfig(request).configure(reviewed_list)
    return render(request, 'reviews/reviewed_list.html', {'reviewed_list': reviewed_list})


@login_required
def emp_recommendation_list(request):
    train_Algorithm()
    # predicted_list(request)
    predicted_list = PossibleResigneeTable(EmpPossibleResigneeReview.objects.all())
    RequestConfig(request).configure(predicted_list)
    return render(request, 'reviews/predicted_list.html', {'predicted_list': predicted_list})

class HRMSRegistrationView(RegistrationView):
    def get_success_url(self, user=None):
        return "reviews/staff"

hrms/reviews/templates/reviews/predicted_list.html
{% extends 'base.html' %}

{% load render_table from django_tables2 %}
{% load static %}

{% block title %}
    <h2>Predicted List</h2>
{% endblock %}

{% block content %}
    {% if predicted_list %}
        {% render_table predicted_list %}
    {% else %}
        <p>No prediction is available.</p>
    {% endif %}

{% endblock %}

hrms/reviews/templates/reviews/review_detail.html
{% extends 'base.html' %}

{% block title %}
<h2><a href="{% url 'reviews:wine_detail' review.wine.id %}">{{ review.wine.name }}</a></h2>
{% endblock %}

{% block content %}
<h4>Rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h4>
<p>{{ review.pub_date }}</p>
<p>{{ review.comment }}</p>
{% endblock %}

hrms/reviews/templates/reviews/review_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    <h1>HRMS</h1> <br>
    <h2>Project Business Goals</h2>
    <div>
        HR Analysis application by utilising machine learning and help to achieve its business to -
        <ul>
            <li>
                Save Cost financially
            </li>
            <li>
                Save brain drain effect
            </li>
            <li>
                Morally Substantial
            </li>
        </ul>
    </div>
    <br>
    <div>
        <h3>Main Function</h3><br>
        <p>
            To build a prediction model to predict which of their
analysis the employee data  and predicting the whether the experienced employee leaving prematurely?
        </p>
    </div>
{% endblock %}

{% block content %}

{% endblock %}

hrms/reviews/templates/reviews/reviewed_list.html
{% extends 'base.html' %}

{% load render_table from django_tables2 %}
{% load static %}

{% block title %}
    <h2>Reviewed Employee List</h2> <br>
{% endblock %}

{% block content %}
    <a href="{% url 'reviews:emp_recommendation_list' %}" class="top-menu"><span class="glyphicon glyphicon-plus">Predict</span></a>
    <br><br>

    {% if reviewed_list %}
        {% render_table reviewed_list %}
    {% else %}
        <p>No Reiviewed Employee is available.</p>
    {% endif %}

{% endblock %}

hrms/reviews/templates/reviews/staff_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
    <h2>Add your review for {{ staff.username }}</h2>
{% endblock %}


{% block content %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'reviews:add_emp_review' staff.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Add
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

hrms/reviews/templates/reviews/staff_list.html
{% extends 'base.html' %}

{% load render_table from django_tables2 %}
{% load static %}

{% block title %}
<h2>Staff List</h2>
{% endblock %}

{% block content %}
{% if staff_list %}
	{% render_table staff_list %}
{% else %}
    <p>No staffs are available.</p>
{% endif %}

{% endblock %}

hrms/reviews/templates/reviews/staff_recommendation_list.html
{% extends 'reviews/staff_list.html' %}

{% block title %}
<h2>Possible Resignee for {{ username }}</h2>
{% endblock %}

hrms/templates/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
    <div class="container">
        <nav class="navbar navbar-default">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'reviews:review_list' %}">HR Management</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    {% if user.is_authenticated %}
                        <li><a href="{% url 'reviews:staff_list' %}">Staff list</a></li>
                        <li><a href="{% url 'reviews:reviewed_list' %}">Reviewed Employee List </a></li>
                        <li><a href="{% url 'reviews:predicted_list' %}">Predicted List </a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'auth:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'auth:login' %}">Login</a></li>
                        <li><a href="/accounts/register">Register</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>


        <h1>{% block title %}(no title){% endblock %}</h1>

        {% bootstrap_messages %}

        {% block content %}(no content){% endblock %}
    </div>

{% endblock %}